// <auto-generated>
//   Do not edit by hand.
// </auto-generated>
namespace SFLib.Diagnostics;

using System;

[AttributeUsage(AttributeTargets.Method)]
public class DebuggerAttribute : Attribute
{
    public bool Log;

    public DebuggerAttribute()
    {
    }
}