// <auto-generated>
//   Do not edit by hand.
// </auto-generated>
namespace SFLib.Collections;

public sealed class Dictionary<K, V>
{
    public int Count => 0;

    public List<K> Keys => default!;

    public List<V> Values => default!;

    public V this[K key]
    {
        get => default!;
        set { }
    }

    public void Add(K key, V value)
    {
    }

    public void Clear()
    {
    }

    public bool ContainsKey(K key)
    {
        return false;
    }

    public V? Get(K key)
    {
        return default;
    }

    public void Set(K key, V value)
    {
    }

    public bool Remove(K key)
    {
        return false;
    }

    public Enumerator GetEnumerator() => default!;

    public class Enumerator
    {
        public KeyValue<K, V> Current => default!;

        public bool MoveNext()
        {
            return false;
        }
    }
}

public class KeyValue<K, V>
{
    public K Key => default!;
    public V Value => default!;
}