// <auto-generated>
//   Do not edit by hand.
// </auto-generated>
namespace SFLib.Collections;

public sealed class Queue<T>
{
    public int Count => 0;

    public void Enqueue(T item)
    {
    }

    public T Dequeue()
    {
        return default!;
    }

    public T Peek()
    {
        return default!;
    }

    public void Clear()
    {
    }

    public bool Contains(T item)
    {
        return false;
    }

    public T[] ToArray()
    {
        return default!;
    }

    public Enumerator GetEnumerator() => default!;

    public class Enumerator
    {
        public T Current => default!;

        public bool MoveNext()
        {
            return false;
        }
    }
}