// <auto-generated>
//   Do not edit by hand.
// </auto-generated>

#nullable enable
#pragma warning disable CS8981, CS1591

namespace SFLib.Interop;

/// <summary>
/// C# interop wrapper for the Lua 5.3 <c>coroutine</c> standard library.
/// All coroutine functions are available in Warcraft III's embedded Lua 5.3 runtime.
/// See <see href="https://www.lua.org/manual/5.3/manual.html#6.2">Lua 5.3 coroutine reference</see>.
/// </summary>
public partial class coroutine : LuaObject
{
    /// <summary>
    /// Creates a new coroutine, with body f. f must be a Lua function.
    /// Returns a Lua object of type "thread" (the coroutine).
    /// </summary>
    /// <param name="f">The coroutine body function.</param>
    /// <returns>A new coroutine thread.</returns>
    public static LuaObject create(LuaObject f) => throw null;

    /// <summary>
    /// Starts or continues the execution of coroutine co.
    /// The first time you resume a coroutine, it starts running its body.
    /// The values val1, ... are passed as arguments to the body function.
    /// If the coroutine has yielded, resume restarts it; the values val1, ... are passed as the results from the yield.
    /// If the coroutine runs without any errors, resume returns true plus any values passed to yield
    /// (if the coroutine yields) or any values returned by the body function (if the coroutine terminates).
    /// If there is any error, resume returns false plus the error message.
    /// </summary>
    /// <param name="co">The coroutine to resume.</param>
    /// <param name="values">Values to pass to the coroutine body or as yield results.</param>
    /// <returns>A tuple of (success, results). In Lua: status, val1, val2, ...</returns>
    public static (bool status, object?[] results) resume(LuaObject co, params object?[] values) => throw null;

    /// <summary>
    /// Suspends the execution of the calling coroutine.
    /// Any arguments to yield are passed as extra results to resume.
    /// </summary>
    /// <param name="values">Values to return to the coroutine's caller.</param>
    /// <returns>Values passed to the next resume call.</returns>
    public static object?[] yield(params object?[] values) => throw null;

    /// <summary>
    /// Returns the status of coroutine co, as a string:
    /// "running", if the coroutine is running (that is, it called status);
    /// "suspended", if the coroutine is suspended in a call to yield, or if it has not started running yet;
    /// "normal" if the coroutine is active but not running (that is, it has resumed another coroutine);
    /// "dead" if the coroutine has finished its body function, or if it has stopped with an error.
    /// </summary>
    /// <param name="co">The coroutine to query.</param>
    /// <returns>A string describing the coroutine status.</returns>
    public static string status(LuaObject co) => throw null;

    /// <summary>
    /// Returns the running coroutine, plus a boolean that is true when the running coroutine is the main one.
    /// In Lua: coroutine, isMain = coroutine.running()
    /// </summary>
    /// <returns>A tuple of (coroutine, isMain).</returns>
    public static (LuaObject coroutine, bool isMain) running() => throw null;

    /// <summary>
    /// Creates a new coroutine, with body f.
    /// f must be a Lua function. Returns a function that resumes the coroutine each time it is called.
    /// Any arguments passed to the function behave as the extra arguments to resume.
    /// Returns the results of the coroutine, after the first yield.
    /// Unlike coroutine.resume, the wrapped function does not return an error flag;
    /// if there is an error, it is propagated.
    /// </summary>
    /// <param name="f">The coroutine body function.</param>
    /// <returns>A function that resumes the coroutine.</returns>
    public static LuaObject wrap(LuaObject f) => throw null;

    /// <summary>
    /// Returns true when the running coroutine can yield.
    /// A coroutine is yieldable when it is not inside a non-yieldable C function.
    /// In the main thread, isyieldable always returns false.
    /// </summary>
    /// <returns><c>true</c> if the running coroutine can yield.</returns>
    public static bool isyieldable() => throw null;
}
