// <auto-generated>
//   Do not edit by hand.
// </auto-generated>

#nullable enable
#pragma warning disable CS8981, CS1591

namespace SFLib.Interop;

/// <summary>
/// C# interop wrapper for the Lua 5.3 <c>os</c> standard library.
/// Only <c>os.clock</c>, <c>os.date</c>, <c>os.difftime</c>, and <c>os.time</c> are available
/// in Warcraft III's embedded Lua 5.3 runtime. The following functions are NOT available
/// and are not included: os.execute, os.exit, os.getenv, os.remove, os.rename, os.setlocale, os.tmpname.
/// See <see href="https://www.lua.org/manual/5.3/manual.html#6.9">Lua 5.3 os reference</see>.
/// </summary>
public partial class os : LuaObject
{
    /// <summary>
    /// Returns an approximation of the amount in seconds of CPU time used by the program.
    /// In Warcraft III, this measures time within the Lua runtime.
    /// </summary>
    /// <returns>CPU time in seconds.</returns>
    public static float clock() => throw null!;

    /// <summary>
    /// If the time argument is present, this is the time to be formatted
    /// (see the os.time function for a description of this value).
    /// Otherwise, date formats the current time.
    /// </summary>
    /// <returns>A string representing the current date and time in "%c" format.</returns>
    public static string date() => throw null!;

    /// <summary>
    /// If the time argument is present, this is the time to be formatted
    /// (see the os.time function for a description of this value).
    /// Otherwise, date formats the current time.
    /// </summary>
    /// <param name="format">The format string (e.g., "%Y-%m-%d", "*t" for table).</param>
    /// <returns>A formatted date string, or a table if format is "*t".</returns>
    public static object date(string format) => throw null!;

    /// <inheritdoc cref="date(string)"/>
    /// <param name="format">The format string.</param>
    /// <param name="time">The time value to format (from os.time).</param>
    /// <returns>A formatted date string, or a table if format is "*t".</returns>
    public static object date(string format, int time) => throw null!;

    /// <summary>
    /// Returns the difference, in seconds, from time t1 to time t2.
    /// In POSIX, Windows, and some other systems, this value is exactly t2-t1.
    /// </summary>
    /// <param name="t2">The later time.</param>
    /// <param name="t1">The earlier time.</param>
    /// <returns>The difference in seconds.</returns>
    public static int difftime(int t2, int t1) => throw null!;

    /// <summary>
    /// Returns the current time when called without arguments, or a time representing the
    /// date and time specified by the given table. This table must have fields year, month,
    /// and day, and may have fields hour, min, sec, and isdst.
    /// </summary>
    /// <returns>The current time as a Unix timestamp (seconds since epoch).</returns>
    public static int time() => throw null!;

    /// <inheritdoc cref="time()"/>
    /// <param name="table">A table with fields: year, month, day, and optionally hour, min, sec, isdst.</param>
    /// <returns>A Unix timestamp for the specified date/time.</returns>
    public static int time(LuaObject table) => throw null!;
}
