// <auto-generated>
//   Do not edit by hand.
// </auto-generated>

#nullable enable
#pragma warning disable CS8981, CS1591

namespace SFLib.Interop;

/// <summary>
/// C# interop wrapper for the Lua 5.3 <c>string</c> standard library.
/// All string functions are available in Warcraft III's embedded Lua 5.3 runtime,
/// except <c>string.dump</c> which is not available.
/// See <see href="https://www.lua.org/manual/5.3/manual.html#6.4">Lua 5.3 string reference</see>.
/// </summary>
public partial class @string : LuaObject
{
    /// <summary>
    /// Returns the internal numerical codes of the characters s[i], s[i+1], ..., s[j].
    /// The default value for i is 1; the default value for j is i.
    /// These indices are corrected following the same rules of string.sub.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <returns>An array of byte values for each character.</returns>
    public static int[] @byte(string s) => throw null!;

    /// <inheritdoc cref="byte(string)"/>
    /// <param name="s">The input string.</param>
    /// <param name="i">The start index (1-based).</param>
    /// <returns>An array of byte values for each character in the range.</returns>
    public static int[] @byte(string s, int i) => throw null!;

    /// <inheritdoc cref="byte(string)"/>
    /// <param name="s">The input string.</param>
    /// <param name="i">The start index (1-based).</param>
    /// <param name="j">The end index (1-based, inclusive).</param>
    /// <returns>An array of byte values for each character in the range.</returns>
    public static int[] @byte(string s, int i, int j) => throw null!;

    /// <summary>
    /// Receives zero or more integers. Returns a string with length equal to the number of arguments,
    /// in which each character has the internal numerical code equal to its corresponding argument.
    /// </summary>
    /// <param name="values">The byte values to convert to characters.</param>
    /// <returns>A string composed of the given byte values.</returns>
    public static string @char(params int[] values) => throw null!;

    /// <summary>
    /// Looks for the first match of the pattern (see §6.4.1) in the string s.
    /// If it finds a match, returns the indices of s where this occurrence starts and ends;
    /// otherwise, returns nil.
    /// A third, optional numerical argument init specifies where to start the search;
    /// its default value is 1 and can be negative.
    /// A fourth optional argument plain turns off the pattern matching facilities,
    /// so the function does a plain "find substring" operation.
    /// </summary>
    /// <param name="s">The string to search in.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <returns>A tuple of (start, end) indices, or <c>null</c> if not found.</returns>
    public static (int start, int end)? find(string s, string pattern) => throw null!;

    /// <inheritdoc cref="find(string, string)"/>
    /// <param name="s">The string to search in.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <param name="init">The start index (1-based, can be negative).</param>
    /// <returns>A tuple of (start, end) indices, or <c>null</c> if not found.</returns>
    public static (int start, int end)? find(string s, string pattern, int init) => throw null!;

    /// <inheritdoc cref="find(string, string)"/>
    /// <param name="s">The string to search in.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <param name="init">The start index (1-based, can be negative).</param>
    /// <param name="plain">If true, disables pattern matching and does plain substring search.</param>
    /// <returns>A tuple of (start, end) indices, or <c>null</c> if not found.</returns>
    public static (int start, int end)? find(string s, string pattern, int init, bool plain) => throw null!;

    /// <summary>
    /// Returns a formatted version of its variable number of arguments following the description given in its first argument.
    /// The format string follows the same rules as the C function sprintf.
    /// </summary>
    /// <param name="format">The format string (e.g., "%s %d", "%.2f").</param>
    /// <param name="values">The values to format.</param>
    /// <returns>The formatted string.</returns>
    public static string format(string format, params object?[] values) => throw null!;

    /// <summary>
    /// Returns an iterator function that, each time it is called, returns the next captures from pattern
    /// (see §6.4.1) over the string s.
    /// </summary>
    /// <param name="s">The string to iterate over.</param>
    /// <param name="pattern">The pattern with captures.</param>
    /// <returns>An iterator function.</returns>
    public static LuaObject gmatch(string s, string pattern) => throw null!;

    /// <summary>
    /// Returns a copy of s in which all (or the first n, if given) occurrences of the pattern
    /// (see §6.4.1) have been replaced by a replacement string specified by repl.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <param name="repl">The replacement string or function.</param>
    /// <returns>A tuple of (result, count) where count is the number of substitutions.</returns>
    public static (string result, int count) gsub(string s, string pattern, string repl) => throw null!;

    /// <inheritdoc cref="gsub(string, string, string)"/>
    /// <param name="s">The input string.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <param name="repl">The replacement string or function.</param>
    /// <param name="n">Maximum number of replacements.</param>
    /// <returns>A tuple of (result, count) where count is the number of substitutions.</returns>
    public static (string result, int count) gsub(string s, string pattern, string repl, int n) => throw null!;

    /// <summary>
    /// Returns its length. The empty string "" has length 0.
    /// Embedded zeros are counted, so "a\000bc\000" has length 5.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <returns>The length of the string.</returns>
    public static int len(string s) => throw null!;

    /// <summary>
    /// Receives a string and returns a copy of this string with all uppercase letters changed to lowercase.
    /// All other characters are left unchanged.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <returns>The lowercase copy.</returns>
    public static string lower(string s) => throw null!;

    /// <summary>
    /// Looks for the first match of the pattern (see §6.4.1) in the string s.
    /// If it finds one, returns the captures from the pattern; otherwise, returns nil.
    /// </summary>
    /// <param name="s">The string to search in.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <returns>The captured substrings, or <c>null</c> if no match.</returns>
    public static string? match(string s, string pattern) => throw null!;

    /// <inheritdoc cref="match(string, string)"/>
    /// <param name="s">The string to search in.</param>
    /// <param name="pattern">The pattern to search for.</param>
    /// <param name="init">The start index (1-based, can be negative).</param>
    /// <returns>The captured substrings, or <c>null</c> if no match.</returns>
    public static string? match(string s, string pattern, int init) => throw null!;

    /// <summary>
    /// Returns a string that is the concatenation of n copies of the string s separated by the string sep.
    /// </summary>
    /// <param name="s">The string to repeat.</param>
    /// <param name="n">The number of repetitions.</param>
    /// <returns>The repeated string.</returns>
    public static string rep(string s, int n) => throw null!;

    /// <inheritdoc cref="rep(string, int)"/>
    /// <param name="s">The string to repeat.</param>
    /// <param name="n">The number of repetitions.</param>
    /// <param name="sep">The separator string between repetitions.</param>
    /// <returns>The repeated string with separators.</returns>
    public static string rep(string s, int n, string sep) => throw null!;

    /// <summary>
    /// Returns a string that is the string s reversed.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <returns>The reversed string.</returns>
    public static string reverse(string s) => throw null!;

    /// <summary>
    /// Returns the substring of the string s that starts at i and continues until j.
    /// i and j can be negative.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <param name="i">The start index (1-based, can be negative).</param>
    /// <returns>The substring from i to the end.</returns>
    public static string sub(string s, int i) => throw null!;

    /// <inheritdoc cref="sub(string, int)"/>
    /// <param name="s">The input string.</param>
    /// <param name="i">The start index (1-based, can be negative).</param>
    /// <param name="j">The end index (1-based, inclusive, can be negative).</param>
    /// <returns>The substring from i to j.</returns>
    public static string sub(string s, int i, int j) => throw null!;

    /// <summary>
    /// Receives a string and returns a copy of this string with all lowercase letters changed to uppercase.
    /// All other characters are left unchanged.
    /// </summary>
    /// <param name="s">The input string.</param>
    /// <returns>The uppercase copy.</returns>
    public static string upper(string s) => throw null!;

    /// <summary>
    /// Returns a binary string containing the values v1, v2, etc. packed in binary form
    /// according to the format string fmt (see §6.4.2).
    /// </summary>
    /// <param name="fmt">The format string describing the binary layout.</param>
    /// <param name="values">The values to pack.</param>
    /// <returns>The packed binary string.</returns>
    public static string pack(string fmt, params object?[] values) => throw null!;

    /// <summary>
    /// Returns the size of a string resulting from string.pack with the given format string fmt.
    /// The format string cannot have the variable-length options 's' or 'z'.
    /// </summary>
    /// <param name="fmt">The format string.</param>
    /// <returns>The size in bytes.</returns>
    public static int packsize(string fmt) => throw null!;

    /// <summary>
    /// Returns the values packed in string s (see string.pack) according to the format string fmt.
    /// An optional pos marks where to start reading in s (default is 1).
    /// After the read values, this function also returns the index of the first unread byte in s.
    /// </summary>
    /// <param name="fmt">The format string describing the binary layout.</param>
    /// <param name="s">The packed binary string to unpack.</param>
    /// <returns>A tuple of (values, position).</returns>
    public static (object?[] values, int position) unpack(string fmt, string s) => throw null!;

    /// <inheritdoc cref="unpack(string, string)"/>
    /// <param name="fmt">The format string describing the binary layout.</param>
    /// <param name="s">The packed binary string to unpack.</param>
    /// <param name="pos">The position to start reading (1-based).</param>
    /// <returns>A tuple of (values, position).</returns>
    public static (object?[] values, int position) unpack(string fmt, string s, int pos) => throw null!;
}
