// <auto-generated>
//   Do not edit by hand.
// </auto-generated>
using System;

#nullable enable
#pragma warning disable CS8981, CS1591

namespace SFLib.Interop;

/// <summary>
/// C# interop wrapper for the Lua 5.3 <c>table</c> standard library.
/// All table functions are available in Warcraft III's embedded Lua 5.3 runtime.
/// See <see href="https://www.lua.org/manual/5.3/manual.html#6.6">Lua 5.3 table reference</see>.
/// </summary>
public partial class table : LuaObject
{
    /// <summary>
    /// Given a list where all elements are strings or numbers, returns the string
    /// <c>list[i]..sep..list[i+1] ··· sep..list[j]</c>.
    /// The default value for sep is the empty string, the default for i is 1,
    /// and the default for j is #list.
    /// If the value of any element is nil, it is skipped.
    /// </summary>
    /// <param name="list">The table to concatenate.</param>
    /// <returns>The concatenated string.</returns>
    public static string concat(LuaObject list) => throw null!;

    /// <inheritdoc cref="concat(LuaObject)"/>
    /// <param name="list">The table to concatenate.</param>
    /// <param name="sep">The separator string.</param>
    /// <returns>The concatenated string.</returns>
    public static string concat(LuaObject list, string sep) => throw null!;

    /// <inheritdoc cref="concat(LuaObject)"/>
    /// <param name="list">The table to concatenate.</param>
    /// <param name="sep">The separator string.</param>
    /// <param name="i">The start index (1-based).</param>
    /// <returns>The concatenated string.</returns>
    public static string concat(LuaObject list, string sep, int i) => throw null!;

    /// <inheritdoc cref="concat(LuaObject)"/>
    /// <param name="list">The table to concatenate.</param>
    /// <param name="sep">The separator string.</param>
    /// <param name="i">The start index (1-based).</param>
    /// <param name="j">The end index (1-based, inclusive).</param>
    /// <returns>The concatenated string.</returns>
    public static string concat(LuaObject list, string sep, int i, int j) => throw null!;

    /// <summary>
    /// Inserts element value at position pos in list, shifting up the elements
    /// <c>list[pos], list[pos+1], ···, list[#list]</c>.
    /// The default value for pos is #list+1, so that a call <c>table.insert(t,x)</c>
    /// inserts x at the end of the list t.
    /// </summary>
    /// <param name="list">The table to insert into.</param>
    /// <param name="value">The value to insert.</param>
    public static void insert(LuaObject list, object? value) => throw null!;

    /// <inheritdoc cref="insert(LuaObject, object?)"/>
    /// <param name="list">The table to insert into.</param>
    /// <param name="pos">The position to insert at (1-based).</param>
    /// <param name="value">The value to insert.</param>
    public static void insert(LuaObject list, int pos, object? value) => throw null!;

    /// <summary>
    /// Moves elements from table a1 to table a2.
    /// <c>a2[f], ···, a2[e], ···</c> = <c>a1[f], ···, a1[e]</c>.
    /// Returns the destination table a2.
    /// </summary>
    /// <param name="a1">The source table.</param>
    /// <param name="f">The first element index in the source.</param>
    /// <param name="e">The last element index in the source (inclusive).</param>
    /// <param name="t">The destination position in a2.</param>
    /// <returns>The destination table.</returns>
    public static LuaObject move(LuaObject a1, int f, int e, int t) => throw null!;

    /// <inheritdoc cref="move(LuaObject, int, int, int)"/>
    /// <param name="a1">The source table.</param>
    /// <param name="f">The first element index in the source.</param>
    /// <param name="e">The last element index in the source (inclusive).</param>
    /// <param name="t">The destination position in a2.</param>
    /// <param name="a2">The destination table (defaults to a1).</param>
    /// <returns>The destination table.</returns>
    public static LuaObject move(LuaObject a1, int f, int e, int t, LuaObject a2) => throw null!;

    /// <summary>
    /// Returns a new table with all arguments stored into keys 1, 2, etc.
    /// and with a field "n" with the total number of arguments.
    /// Note that the resulting table may not be a sequence.
    /// </summary>
    /// <param name="values">The values to pack into a table.</param>
    /// <returns>A new table with the packed values.</returns>
    public static LuaObject pack(params object?[] values) => throw null!;

    /// <summary>
    /// Removes from list the element at position pos, shifting down the elements
    /// <c>list[pos+1], list[pos+2], ···, list[#list]</c> and erasing element <c>list[#list]</c>.
    /// Returns the value of the removed element.
    /// The default value for pos is #list, so that a call <c>table.remove(t)</c>
    /// removes the last element of the list t.
    /// </summary>
    /// <param name="list">The table to remove from.</param>
    /// <returns>The removed value.</returns>
    public static object? remove(LuaObject list) => throw null!;

    /// <inheritdoc cref="remove(LuaObject)"/>
    /// <param name="list">The table to remove from.</param>
    /// <param name="pos">The position to remove from (1-based).</param>
    /// <returns>The removed value.</returns>
    public static object? remove(LuaObject list, int pos) => throw null!;

    /// <summary>
    /// Sorts list elements in a given order, in-place, from <c>list[1]</c> to <c>list[#list]</c>.
    /// If comp is given, then it must be a function that receives two list elements
    /// and returns true when the first element must come before the second in the final order.
    /// If comp is not given, then the standard Lua operator &lt; is used instead.
    /// </summary>
    /// <param name="list">The table to sort.</param>
    public static void sort(LuaObject list) => throw null!;

    /// <inheritdoc cref="sort(LuaObject)"/>
    /// <param name="list">The table to sort.</param>
    /// <param name="comp">The comparison function.</param>
    public static void sort(LuaObject list, Func<LuaObject, LuaObject, bool> comp) => throw null!;

    /// <summary>
    /// Returns the elements from the given table.
    /// This function is equivalent to <c>return list[i], list[i+1], ···, list[j]</c>.
    /// By default, i is 1 and j is #list.
    /// </summary>
    /// <param name="list">The table to unpack.</param>
    /// <returns>The values from the table.</returns>
    public static object?[] unpack(LuaObject list) => throw null!;

    /// <inheritdoc cref="unpack(LuaObject)"/>
    /// <param name="list">The table to unpack.</param>
    /// <param name="i">The start index (1-based).</param>
    /// <returns>The values from the table.</returns>
    public static object?[] unpack(LuaObject list, int i) => throw null!;

    /// <inheritdoc cref="unpack(LuaObject)"/>
    /// <param name="list">The table to unpack.</param>
    /// <param name="i">The start index (1-based).</param>
    /// <param name="j">The end index (1-based, inclusive).</param>
    /// <returns>The values from the table.</returns>
    public static object?[] unpack(LuaObject list, int i, int j) => throw null!;
}
