// <auto-generated>
//   Do not edit by hand.
// </auto-generated>

#nullable enable
#pragma warning disable CS8981, CS1591

namespace SFLib.Interop;

/// <summary>
/// C# interop wrapper for the Lua 5.3 <c>utf8</c> standard library.
/// All utf8 functions are available in Warcraft III's embedded Lua 5.3 runtime.
/// See <see href="https://www.lua.org/manual/5.3/manual.html#6.5">Lua 5.3 utf8 reference</see>.
/// </summary>
public partial class utf8 : LuaObject
{
    /// <summary>
    /// Receives zero or more integers, converts each one to its corresponding UTF-8 byte sequence
    /// and returns a string with the concatenation of all these sequences.
    /// </summary>
    /// <param name="values">Unicode code points.</param>
    /// <returns>A UTF-8 encoded string.</returns>
    public static string @char(params int[] values) => throw null!;

    /// <summary>
    /// Returns the code points (as integers) from all characters in s that start between byte position i and j.
    /// It raises an error if it finds any invalid byte sequence.
    /// </summary>
    /// <param name="s">The UTF-8 string.</param>
    /// <returns>An array of Unicode code points.</returns>
    public static int[] codepoint(string s) => throw null!;

    /// <inheritdoc cref="codepoint(string)"/>
    /// <param name="s">The UTF-8 string.</param>
    /// <param name="i">The start byte position (1-based).</param>
    /// <returns>An array of Unicode code points.</returns>
    public static int[] codepoint(string s, int i) => throw null!;

    /// <inheritdoc cref="codepoint(string)"/>
    /// <param name="s">The UTF-8 string.</param>
    /// <param name="i">The start byte position (1-based).</param>
    /// <param name="j">The end byte position (1-based, inclusive).</param>
    /// <returns>An array of Unicode code points.</returns>
    public static int[] codepoint(string s, int i, int j) => throw null!;

    /// <summary>
    /// Returns an iterator function that traverses the string s, yielding the position and code point of each character.
    /// It raises an error if it finds any invalid byte sequence.
    /// </summary>
    /// <param name="s">The UTF-8 string.</param>
    /// <returns>An iterator function yielding (position, codepoint) pairs.</returns>
    public static LuaObject codes(string s) => throw null!;

    /// <summary>
    /// Returns the number of UTF-8 characters in the string s that start between positions i and j.
    /// The default for i is 1 and for j is -1.
    /// If it finds any invalid byte sequence, returns a false value plus the position of the first invalid byte.
    /// </summary>
    /// <param name="s">The UTF-8 string.</param>
    /// <returns>The number of UTF-8 characters, or (nil, position) on error.</returns>
    public static int? len(string s) => throw null!;

    /// <inheritdoc cref="len(string)"/>
    /// <param name="s">The UTF-8 string.</param>
    /// <param name="i">The start byte position (1-based).</param>
    /// <returns>The number of UTF-8 characters, or (nil, position) on error.</returns>
    public static int? len(string s, int i) => throw null!;

    /// <inheritdoc cref="len(string)"/>
    /// <param name="s">The UTF-8 string.</param>
    /// <param name="i">The start byte position (1-based).</param>
    /// <param name="j">The end byte position (1-based, inclusive).</param>
    /// <returns>The number of UTF-8 characters, or (nil, position) on error.</returns>
    public static int? len(string s, int i, int j) => throw null!;

    /// <summary>
    /// Returns the position (in bytes) where the encoding of the n-th character of s
    /// starts (counting from position i). A negative n means characters before position i.
    /// The default for i is 1 when n is non-negative and #s + 1 otherwise,
    /// so that utf8.offset(s, -n) gets the offset of the n-th character from the end of the string.
    /// </summary>
    /// <param name="s">The UTF-8 string.</param>
    /// <param name="n">The character index (1-based, can be negative).</param>
    /// <returns>The byte position of the n-th character, or nil if out of range.</returns>
    public static int? offset(string s, int n) => throw null!;

    /// <inheritdoc cref="offset(string, int)"/>
    /// <param name="s">The UTF-8 string.</param>
    /// <param name="n">The character index (1-based, can be negative).</param>
    /// <param name="i">The byte position to start from (1-based).</param>
    /// <returns>The byte position of the n-th character, or nil if out of range.</returns>
    public static int? offset(string s, int n, int i) => throw null!;

    /// <summary>
    /// The pattern (a string, not a function) "[\0-\x7F\xC2-\xF4][\x80-\xBF]*",
    /// which matches exactly one UTF-8 byte sequence, assuming that the subject is a valid UTF-8 string.
    /// </summary>
    public static string charpattern => throw null!;
}
