// <auto-generated>
//   Generated by sf-jassgen from common.j / blizzard.j.
//   Do not edit by hand; re-run the generator instead.
// </auto-generated>
#nullable enable
#pragma warning disable CS8981, CS1591

public static partial class JASS
{
    public static int FourCC(string val) => throw null!;
}
