// <auto-generated>
//   Do not edit by hand.
// </auto-generated>
#nullable enable
namespace SFLib;

using System;

[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
public sealed class LuaAttribute : Attribute
{
    public string? Name;
    public string? StaticMethod;
    public string? Method;
    public string? Module;
    public string? Class;
    public string? Require;
    public bool TableLiteral;

    public LuaAttribute()
    {
    }
}

public class LuaObject
{
    public LuaObject()
    {
    }
}

public static class LuaInterop
{
    public static LuaObject CreateTable() => default!;

    public static LuaObject Require(string moduleName) => default!;

    public static T Require<T>(string moduleName) => default!;

    public static T Get<T>(LuaObject target, string name) => default!;

    public static T GetGlobal<T>(string name) => default!;

    public static void Set(LuaObject target, string name, object? value)
    {
    }

    public static void SetGlobal(string name, object? value)
    {
    }

    public static void Call(LuaObject target, string functionName, params object?[] arguments)
    {
    }

    public static T Call<T>(LuaObject target, string functionName, params object?[] arguments) => default!;

    public static void CallMethod(LuaObject target, string methodName, params object?[] arguments)
    {
    }

    public static T CallMethod<T>(LuaObject target, string methodName, params object?[] arguments) => default!;

    public static void CallGlobal(string functionName, params object?[] arguments)
    {
    }

    public static T CallGlobal<T>(string functionName, params object?[] arguments) => default!;
}
